<a href="https://colab.research.google.com/github/rojanridegreecollege/Python-mini-projects/blob/main/Introduction_to_Numpyipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Nump-Numatic python
#Most powerful package-Libarary

#Numpy-Dimensions

#A- One Dimensional Array
#[A,B]|| [A
#.        B]-Two Dimensional Array-Row||colum
# Three Dimensional
#Array- Storing,Manipulating,similar Data type
#Faster than any mathematical functions
#convinient compared to other packages
#Memory efficiency
#support multi dimensional arras

#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)

In [2]:
# install Numpy_pip3 install Numpy//pip install numpy

In [57]:
import  numpy as np

In [58]:
#create a numpy array
#1D array

arr1D=np.array([1,2,3,4,5,])
print(arr1D)

[1 2 3 4 5]


In [ ]:
#creting 2D array _Matrix
arr2D=np.array([
               [1,2,3],[4,5,6]
          ])

In [ ]:
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [5]:
#creating arrays with default values
allzeros=np.zeros((2,3))

In [59]:
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
#creating  matrix with all values of elementsas'1'
allones=np.ones((2,3))

In [62]:
print(allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
#creating matrix  with  all values of elements'constant value_n~full value'
allconstant=np.full((2,3),6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create  an identity matrix_I_Square  Matrix
identity =np.eye(4)
print(identity)
#Identity Matrix_ Aiti= 1&&Aij=0
#For all A Belongs to RMxN

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating  random Matrices

#between 0 and 1
ran1=np.random.rand(3,3)

In [ ]:
#between a and

In [10]:
print(3,3)

3 3


In [11]:
#between a and b
rand2=np.random.randint(10,20,(3,3))

In [64]:
print(rand2)

[[16 11 12]
 [18 18 11]
 [18 12 11]]


In [65]:
#Array properties
arr=np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
#Shape of array
print(f"\n The shape of the array is {arr.shape}")
#Size of array
print (f'The size of the array is {arr.size}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')


 The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2


In [ ]:
#Indexing and slicing
#Access the elements in 1D Array
arr=np.array([1,2,3,4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [ ]:
#Slicing the elements
print (arr[0:3])
#Acess the element in 2D Array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#first row  with all columns
print(arr2[:,0])#firdt column  with  all rows

[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
L1=[]
[L1.append(_) for _ in range(10)]

L1=[]
[L1.append(_) for _ in range(10)]

import numpy as np
L1=np.arange(0,10)
print(L1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Mathematical operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print (f'The product of a and b is{a*b}')
print(f'The division of a and b is{a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is[ 3  8 15]
The division of a and b is[0.33333333 0.5        0.6       ]


In [24]:
#Matrix Multiplication
b1=np.array([[2,3,0],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])
#Dot.product
C=np.dot(b1,b2)
print(C)

[[31 36]
 [35 48]]


In [25]:
print(b1)

[[2 3 0]
 [2 3 4]]


In [26]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [27]:
[
  [22,31],
  [35,48]
]

[[22, 31], [35, 48]]

In [28]:
import numpy as np

In [30]:
#Recap
arr =np.array([[1,2,3],[4,5,6]])

In [31]:
#Dot product_m*n//n*p
arr1=np.random.randint(1,2,(3,1))

In [32]:
arr.shape
arr1.shape

(3, 1)

In [33]:
result=np.dot(arr,arr1)

In [34]:
print(result)

[[ 6]
 [15]]


In [35]:
r1=np.random.randint (10,20,(3,3))
print (r1)

[[16 18 18]
 [11 19 18]
 [17 13 16]]


In [36]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#r1.I
result2=np.dot(r1,r2)

In [38]:
print(result2)

[[16. 18. 18.]
 [11. 19. 18.]
 [17. 13. 16.]]


In [39]:
#M.I=I.M=M

In [40]:
#A.B!=B.A

In [41]:
# Mathematical operations
#+-*/
t1=np.random.randint (3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [45]:
print(t1)
print(t2)

[[5 4 5]
 [3 5 4]
 [3 4 5]]
[[4 4 5]
 [4 5 4]
 [5 5 4]]


In [46]:
t3=t1*t2

In [47]:
print(t3)

[[20 16 25]
 [12 25 16]
 [15 20 20]]


In [48]:
#Matrix multiplication
result=np.dot(arr,arr1)

In [49]:
# statistical operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [50]:
print(median)

20.0


In [51]:
print(std)

4.184037863058384


In [52]:
std*std

17.506172839506167

In [69]:
#Trignometric functions
#Sin(x)
#Cos(x)
#Tan(x)_sin(x)/cod(x)
#Cosec_1/sin(x)
#Sec_1/cos(x)
#Cot_1/tan(x)
#angle=np.array ([0,15,30,45,60,75,90])
#sin(array)

In [72]:
#angle=np.array([0,15,30,45,60,75,90])
#sin(array)

In [78]:
print(result)

[[ 6]
 [15]]


In [82]:
arr=np.array([1,2,3,4,5,6])

In [83]:
#Reshape the array
reshspedarr=arr.reshape(3,2)

In [84]:
print(reshspedarr)

[[1 2]
 [3 4]
 [5 6]]


In [87]:
#convert/flatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[1 2 3 4 5 6]


In [96]:
#staking the data
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

In [98]:
print(np.vstack((arr1,arr2)))

[[ 1  2  3  4]
 [10 20 30 40]]


In [100]:
#vertical stacking
arr3=np.vstack((arr1,arr3))
print(f"The shape of arr3 is {arr3.shape}")

The shape of arr3 is (3, 4)


In [106]:
#Horizantal stacking
arr5=np.hstack((arr1,arr2))
print(f"The shape of arr5 is {arr5.shape}")

The shape of arr5 is (8,)


In [107]:
#Filtering
arr=np.array ([10,20,30,40,50,60,70,80])
fart=arr[arr>40]

In [109]:
print(arr)

[10 20 30 40 50 60 70 80]
