<a href="https://colab.research.google.com/github/rojanridegreecollege/Python-mini-projects/blob/main/Numpyipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Nump-Numatic python
#Most powerful package-Libarary

#Numpy-Dimensions

#A- One Dimensional Array
#[A,B]|| [A
#.        B]-Two Dimensional Array-Row||colum
# Three Dimensional
#Array- Storing,Manipulating,similar Data type
#Faster than any mathematical functions
#convinient compared to other packages
#Memory efficiency
#support multi dimensional arras

#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)

In [2]:
# install Numpy_pip3 install Numpy//pip install numpy

In [3]:
import  numpy as np

In [4]:
#create a numpy array
#1D array

arr1D=np.array([1,2,3,4,5,])
print(arr1D)

[1 2 3 4 5]


In [ ]:
#creting 2D array _Matrix
arr2D=np.array([
               [1,2,3],[4,5,6]
          ])

In [ ]:
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [5]:
#creating arrays with default values
allzeros=np.zeros((2,3))

In [6]:
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#creating  matrix with all values of elementsas'1'
allones=np.ones((2,3))

In [ ]:
print(allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#creating matrix  with  all values of elements'constant value_n~full value'
allconstant=np.full((2,3),6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create  an identity matrix_I_Square  Matrix
identity =np.eye(4)
print(identity)
#Identity Matrix_ Aiti= 1&&Aij=0
#For all A Belongs to RMxN

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating  random Matrices

#between 0 and 1
ran1=np.random.rand(3,3)

In [ ]:
#between a and

In [ ]:
print(3,3)

3 3


In [9]:
#between a and b
rand2=np.random.randint(10,20,(3,3))

In [10]:
print(rand2)

[[19 16 13]
 [15 12 19]
 [11 15 14]]


In [11]:
#Array properties
arr=np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

[[1 2 3 4]
 [2 3 4 5]]


In [17]:
#Shape of array
print(f"\n The shape of the array is {arr.shape}")
#Size of array
print (f'The size of the array is {arr.size}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')
#Data type of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is {arr.ndim}')


 The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2
The Data type of the array is int64
The Dimensions of the array is 2


In [18]:
#Indexing and slicing
#Access the elements in 1D Array
arr=np.array([1,2,3,4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [19]:
#Slicing the elements
print (arr[0:3])
#Acess the element in 2D Array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#first row  with all columns
print(arr2[:,0])#firdt column  with  all rows

[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [24]:
L1=[]
[L1.append(_) for _ in range(10)]

L1=[]
[L1.append(_) for _ in range(10)]

import numpy as np
L1=np.arange(0,10)
print(L1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# Mathematical operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print (f'The product of a and b is{a*b}')
print(f'The division of a and b is{a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is[ 3  8 15]
The division of a and b is[0.33333333 0.5        0.6       ]


In [33]:
#Matrix Multiplication
b1=np.array([[2,3,0],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])
#Dot.product
C=np.dot(b1,b2)
print(C)

[[31 36]
 [35 48]]


In [34]:
print(b1)

[[2 3 0]
 [2 3 4]]


In [36]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [37]:
[
  [22,31],
  [35,48]
]

[[22, 31], [35, 48]]